USE pds;
-- 1
SELECT COUNT(DISTINCT JOB_ID) AS NUMBER_OF_POSITIONS FROM employees;
-- 2
SELECT AVG(SALARY) AS DEP_90_AVERAGE_SALARY, COUNT(EMPLOYEE_ID) AS DEP_90_TOTAL_EMPLOYEES 
FROM employees WHERE DEPARTMENT_ID = 90;
-- 3
SELECT JOB_ID, COUNT(*) AS NUMBER_OF_EMPLOYEES_WITH_SAME_JOB_ID FROM employees
GROUP BY JOB_ID
HAVING COUNT(*) > 1;
-- 4
SELECT FIRST_NAME, LAST_NAME, employees.DEPARTMENT_ID, DEPARTMENT_NAME FROM employees, departments
WHERE departments.DEPARTMENT_ID = employees.DEPARTMENT_ID
ORDER BY DEPARTMENT_NAME;
-- 5
SELECT FIRST_NAME, LAST_NAME, JOB_ID, DEPARTMENT_ID FROM employees
JOIN departments USING (DEPARTMENT_ID)
JOIN locations USING (LOCATION_ID)
WHERE CITY = "London";